/**
 * hello-mcp
 * A minimal MCP server example demonstrating the basic structure.
 * Generated by Plugin Factory v1.0
 */

import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { z } from 'zod';

const CONFIG = {
  name: 'hello-mcp',
  version: '1.0.0',
};

const server = new McpServer({
  name: CONFIG.name,
  version: CONFIG.version,
});

// =============================================================================
// TOOLS
// =============================================================================

/**
 * greet - A simple greeting tool
 */
server.tool(
  'greet',
  'Generate a friendly greeting for someone',
  {
    name: z.string().describe('The name of the person to greet'),
    style: z.enum(['formal', 'casual', 'enthusiastic']).optional().describe('The greeting style'),
  },
  async ({ name, style = 'casual' }) => {
    console.error(`[${CONFIG.name}] greet called:`, { name, style });

    let greeting: string;
    switch (style) {
      case 'formal':
        greeting = `Good day, ${name}. It is a pleasure to make your acquaintance.`;
        break;
      case 'enthusiastic':
        greeting = `Hey ${name}! So great to meet you! This is AWESOME!`;
        break;
      case 'casual':
      default:
        greeting = `Hi ${name}! Nice to meet you.`;
    }

    return {
      content: [
        {
          type: 'text',
          text: greeting,
        },
      ],
    };
  }
);

// =============================================================================
// RESOURCES
// =============================================================================

/**
 * hello://info - Server information resource
 */
server.resource(
  'hello://info',
  'Information about the hello-mcp server',
  async () => {
    return {
      contents: [
        {
          uri: 'hello://info',
          mimeType: 'application/json',
          text: JSON.stringify({
            name: CONFIG.name,
            version: CONFIG.version,
            description: 'A minimal MCP server example',
            tools: ['greet'],
            resources: ['hello://info'],
          }, null, 2),
        },
      ],
    };
  }
);

// =============================================================================
// SERVER STARTUP
// =============================================================================

async function main() {
  process.on('SIGTERM', () => {
    console.error(`[${CONFIG.name}] SIGTERM received`);
    process.exit(0);
  });

  process.on('SIGINT', () => {
    console.error(`[${CONFIG.name}] SIGINT received`);
    process.exit(0);
  });

  const transport = new StdioServerTransport();
  await server.connect(transport);

  console.error(`[${CONFIG.name}] MCP server v${CONFIG.version} running on stdio`);
}

main().catch((error) => {
  console.error(`[${CONFIG.name}] Fatal error:`, error);
  process.exit(1);
});
