/**
 * Hello Agent
 * A simple greeting agent that demonstrates the Agent Factory pattern.
 *
 * Generated by Agent Factory v1.0
 */

import { createServer, IncomingMessage, ServerResponse } from 'node:http';

// ============================================================
// CONFIGURATION
// ============================================================

const CONFIG = {
  name: 'hello-agent',
  version: '1.0.0',
  port: parseInt(process.env.PORT || '3000', 10)
};

// ============================================================
// TYPES
// ============================================================

interface ProcessRequest {
  input: string;
  context?: Record<string, unknown>;
}

interface ProcessResponse {
  response: string;
  metadata?: Record<string, unknown>;
}

// ============================================================
// MAIN AGENT LOGIC
// ============================================================

function getTimeGreeting(): string {
  const hour = new Date().getHours();
  if (hour < 12) return 'Good morning';
  if (hour < 17) return 'Good afternoon';
  return 'Good evening';
}

/**
 * Process user input and return a greeting.
 *
 * In a real agent, this would call an LLM.
 * This example shows the structure without needing API keys.
 */
async function processInput(input: string, _context?: Record<string, unknown>): Promise<string> {
  const name = input.trim() || 'friend';
  const greeting = getTimeGreeting();
  const time = new Date().toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });

  // TODO: In a real agent, you would:
  // 1. Send input to LLM with system prompt
  // 2. Handle tool calls if needed
  // 3. Return LLM's response
  //
  // Example with OpenAI:
  // import OpenAI from 'openai';
  // const openai = new OpenAI();
  // const response = await openai.chat.completions.create({
  //   model: 'gpt-4',
  //   messages: [{ role: 'user', content: `Greet ${name}` }]
  // });
  // return response.choices[0].message.content;

  return `${greeting}, ${name}! It's currently ${time}. Welcome to Agent Factory!`;
}

// ============================================================
// HTTP SERVER
// ============================================================

function parseBody(req: IncomingMessage): Promise<ProcessRequest> {
  return new Promise((resolve, reject) => {
    let body = '';
    req.on('data', (chunk: Buffer) => body += chunk.toString());
    req.on('end', () => {
      try {
        resolve(body ? JSON.parse(body) : {});
      } catch {
        reject(new Error('Invalid JSON'));
      }
    });
    req.on('error', reject);
  });
}

function sendJSON(res: ServerResponse, status: number, data: unknown): void {
  res.writeHead(status, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify(data));
}

const server = createServer(async (req: IncomingMessage, res: ServerResponse) => {
  // CORS
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') {
    res.writeHead(204);
    res.end();
    return;
  }

  const url = new URL(req.url || '/', `http://localhost:${CONFIG.port}`);

  // Health check
  if (req.method === 'GET' && url.pathname === '/health') {
    return sendJSON(res, 200, { status: 'ok', name: CONFIG.name, version: CONFIG.version });
  }

  // Info
  if (req.method === 'GET' && url.pathname === '/') {
    return sendJSON(res, 200, {
      name: CONFIG.name,
      version: CONFIG.version,
      description: 'A simple greeting agent',
      endpoints: {
        'GET /health': 'Health check',
        'POST /process': 'Process input'
      }
    });
  }

  // Main processing endpoint
  if (req.method === 'POST' && url.pathname === '/process') {
    try {
      const body = await parseBody(req);
      if (!body.input) {
        return sendJSON(res, 400, { error: 'Missing "input" field' });
      }
      const response = await processInput(body.input, body.context);
      return sendJSON(res, 200, { response } as ProcessResponse);
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Unknown error';
      return sendJSON(res, 500, { error: message });
    }
  }

  sendJSON(res, 404, { error: 'Not found' });
});

server.listen(CONFIG.port, () => {
  console.log(`
╔══════════════════════════════════════════════════════════════╗
║  ${CONFIG.name} v${CONFIG.version}
║  Running at http://localhost:${CONFIG.port}
╚══════════════════════════════════════════════════════════════╝

Endpoints:
  GET  /          - Info
  GET  /health    - Health check
  POST /process   - Process input

Test:
  curl -X POST http://localhost:${CONFIG.port}/process \\
    -H "Content-Type: application/json" \\
    -d '{"input": "World"}'
`);
});
