#!/bin/bash
#
# Upstream Reference Synchronization
# 
# This script enforces the "Canonical Docs + Upstream Reference Synchronization" policy
# by verifying vendor docs exist and creating/maintaining the required documentation
# infrastructure for every pipeline run.
#
# Exit codes:
#   0 = All documentation infrastructure verified and current
#   1 = Missing vendor docs, failed to create required directories, or sync failures
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"

# Color output for readability
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo "🔄 Upstream Reference Synchronization"
echo "======================================"
echo ""

# Track sync status
SYNC_FAILED=false

# Function to verify vendor documentation exists
verify_vendor_docs() {
    echo "📚 Verifying vendor documentation..."
    
    local vendor_dir="$REPO_ROOT/vendor"
    local expo_docs="$vendor_dir/expo-docs"
    local revenuecat_docs="$vendor_dir/revenuecat-docs"
    local revenuecat_llms="$revenuecat_docs/llms.txt"
    
    # Check vendor directory structure
    if [[ ! -d "$vendor_dir" ]]; then
        echo -e "${RED}❌ FATAL: vendor/ directory not found at $vendor_dir${NC}"
        return 1
    fi
    
    # Check Expo docs
    if [[ ! -d "$expo_docs" ]]; then
        echo -e "${RED}❌ FATAL: vendor/expo-docs/ not found${NC}"
        echo -e "   ${YELLOW}This directory is required for Expo SDK compatibility enforcement${NC}"
        return 1
    else
        echo -e "${GREEN}✅ vendor/expo-docs/ verified${NC}"
    fi
    
    # Check RevenueCat docs
    if [[ ! -d "$revenuecat_docs" ]]; then
        echo -e "${RED}❌ FATAL: vendor/revenuecat-docs/ not found${NC}"
        echo -e "   ${YELLOW}This directory is required for RevenueCat integration${NC}"
        return 1
    else
        echo -e "${GREEN}✅ vendor/revenuecat-docs/ verified${NC}"
    fi
    
    # Check RevenueCat LLMs index
    if [[ ! -f "$revenuecat_llms" ]]; then
        echo -e "${RED}❌ FATAL: vendor/revenuecat-docs/llms.txt not found${NC}"
        echo -e "   ${YELLOW}This file is the canonical RevenueCat documentation index${NC}"
        return 1
    else
        echo -e "${GREEN}✅ vendor/revenuecat-docs/llms.txt verified${NC}"
    fi
    
    echo ""
    return 0
}

# Function to create app documentation infrastructure
create_app_docs() {
    echo "📝 Creating app documentation infrastructure..."
    
    local app_docs="$REPO_ROOT/app/_docs"
    
    # Create app/_docs/ directory
    if [[ ! -d "$app_docs" ]]; then
        echo "   Creating app/_docs/ directory..."
        mkdir -p "$app_docs"
    fi
    
    # Initialize React Native upstream cache using dedicated script
    echo "   Initializing React Native upstream cache..."
    if "$SCRIPT_DIR/rn_upstream_cache.sh" initialize >/dev/null 2>&1; then
        echo "   ✅ RN upstream cache initialized"
    else
        echo "   ❌ RN upstream cache initialization failed"
        return 1
    fi
    
    # Create app/_docs/INDEX.md
    local index_file="$app_docs/INDEX.md"
    if [[ ! -f "$index_file" ]]; then
        echo "   Creating app/_docs/INDEX.md..."
        cat > "$index_file" << 'EOF'
# App Documentation Index

**Generated**: Auto-generated by upstream_reference_sync.sh  
**Purpose**: Track documentation sources used in this pipeline run

## Vendor Documentation References

### Expo SDK Documentation
- **Source**: `vendor/expo-docs/`
- **Status**: Verified present
- **Used For**: Expo SDK compatibility validation, dependency resolution

### RevenueCat Documentation  
- **Source**: `vendor/revenuecat-docs/`
- **Index**: `vendor/revenuecat-docs/llms.txt`
- **Status**: Verified present
- **Used For**: Subscription implementation, paywall integration

## Run-Specific Documentation

This section will be populated during pipeline execution with any additional
documentation sources required for this specific run.

## React Native Upstream Cache

- **Cache Location**: `app/_upstream/react-native/`
- **Manifest**: `app/_upstream/react-native/manifest.json`
- **Purpose**: Local cache for React Native upstream references

## Documentation Policy Compliance

This pipeline run enforces the "Canonical Docs + Upstream Reference Synchronization" policy.
All technical decisions must be grounded in locally cached, authoritative sources.

EOF
    else
        echo "   app/_docs/INDEX.md already exists"
    fi
    
    # Create app/_docs/sources.json
    local sources_file="$app_docs/sources.json"
    if [[ ! -f "$sources_file" ]]; then
        echo "   Creating app/_docs/sources.json..."
        local timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        cat > "$sources_file" << EOF
{
  "documentation_sources": [
    {
      "url": null,
      "local_path": "vendor/expo-docs/",
      "verified_at_iso": "$timestamp",
      "sha256": "vendor_directory",
      "used_for": ["expo_sdk_compatibility", "dependency_resolution"]
    },
    {
      "url": null,
      "local_path": "vendor/revenuecat-docs/",
      "verified_at_iso": "$timestamp", 
      "sha256": "vendor_directory",
      "used_for": ["subscription_implementation", "paywall_integration"]
    }
  ],
  "last_updated": "$timestamp",
  "policy_version": "canonical_docs_v1"
}
EOF
    else
        echo "   app/_docs/sources.json already exists"
    fi
    
    # RN upstream cache is now initialized by dedicated script above
    
    echo -e "${GREEN}✅ App documentation infrastructure created${NC}"
    echo ""
}

# Function to verify documentation infrastructure integrity
verify_docs_integrity() {
    echo "🔍 Verifying documentation infrastructure integrity..."
    
    local required_files=(
        "app/_docs/INDEX.md"
        "app/_docs/sources.json"
        "app/_upstream/react-native/manifest.json"
        "app/_upstream/react-native/INDEX.md"
    )
    
    local missing_files=()
    
    for file in "${required_files[@]}"; do
        local full_path="$REPO_ROOT/$file"
        if [[ -f "$full_path" ]]; then
            echo -e "   ${GREEN}✅ $file${NC}"
        else
            echo -e "   ${RED}❌ MISSING: $file${NC}"
            missing_files+=("$file")
        fi
    done
    
    if [[ ${#missing_files[@]} -gt 0 ]]; then
        echo -e "${RED}❌ Missing ${#missing_files[@]} required documentation files${NC}"
        return 1
    else
        echo -e "${GREEN}✅ All required documentation files present${NC}"
    fi
    
    echo ""
    return 0
}

# Function to create provenance stamp
create_provenance_stamp() {
    echo "📋 Creating synchronization provenance stamp..."
    
    local stamp_file="$REPO_ROOT/app/_docs/sync_provenance.json"
    local timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    local git_hash=$(cd "$REPO_ROOT" && git rev-parse HEAD 2>/dev/null || echo "unknown")
    
    cat > "$stamp_file" << EOF
{
  "sync_event": {
    "timestamp": "$timestamp",
    "script": "scripts/upstream_reference_sync.sh",
    "git_hash": "$git_hash",
    "policy_enforced": "canonical_docs_upstream_reference_sync",
    "vendor_docs_verified": true,
    "app_docs_created": true,
    "upstream_cache_initialized": true
  },
  "compliance_status": "enforced",
  "next_sync_trigger": "stage_02_or_stage_10_start"
}
EOF
    
    echo -e "${GREEN}✅ Provenance stamp created: $stamp_file${NC}"
    echo ""
}

# Main execution
main() {
    echo "Starting upstream reference synchronization..."
    echo ""
    
    # Step 1: Verify vendor documentation
    if ! verify_vendor_docs; then
        echo -e "${RED}❌ SYNC FAILED: Vendor documentation verification failed${NC}"
        return 1
    fi
    
    # Step 2: Create app documentation infrastructure
    if ! create_app_docs; then
        echo -e "${RED}❌ SYNC FAILED: Could not create app documentation infrastructure${NC}"
        return 1
    fi
    
    # Step 3: Verify all required files exist
    if ! verify_docs_integrity; then
        echo -e "${RED}❌ SYNC FAILED: Documentation infrastructure integrity check failed${NC}"
        return 1
    fi
    
    # Step 4: Create provenance stamp
    create_provenance_stamp
    
    echo -e "${GREEN}✅ UPSTREAM REFERENCE SYNC COMPLETE${NC}"
    echo ""
    echo -e "${BLUE}Documentation infrastructure verified and ready for pipeline execution.${NC}"
    echo -e "${BLUE}All stages must now consult local vendor docs and record citations.${NC}"
    
    return 0
}

# Execute main function
main "$@"