/**
 * Codebase Explainer Agent
 * An AI agent that explores and explains unfamiliar codebases.
 *
 * Architecture: Rig-aligned with typed tools and execution loop
 * @see https://github.com/0xPlaygrounds/rig
 *
 * Generated by Agent Factory v3.0
 */

import { createServer, IncomingMessage, ServerResponse } from 'node:http';
import { logger } from './lib/logger.js';
import { ValidationError, handleError } from './lib/errors.js';
import { isPathAllowed } from './lib/path-validator.js';
import {
  createCodebaseExplainerAgent,
  AgentExecutionLoop,
  ExplainRequestSchema,
  ExplainRequest,
  ExplainResponse,
} from './agent/index.js';

// ============================================================================
// Configuration
// ============================================================================

const CONFIG = {
  name: 'codebase-explainer',
  version: '1.0.0',
  port: parseInt(process.env.PORT || '8080', 10),
};

// Validate required environment variables
if (!process.env.OPENAI_API_KEY) {
  console.error('ERROR: OPENAI_API_KEY environment variable is required');
  process.exit(1);
}

// ============================================================================
// HTTP Utilities
// ============================================================================

function parseBody(req: IncomingMessage): Promise<unknown> {
  return new Promise((resolve, reject) => {
    let body = '';
    req.on('data', (chunk: Buffer) => (body += chunk.toString()));
    req.on('end', () => {
      try {
        resolve(body ? JSON.parse(body) : {});
      } catch {
        reject(new ValidationError('Invalid JSON body'));
      }
    });
    req.on('error', reject);
  });
}

function sendJSON(res: ServerResponse, status: number, data: unknown): void {
  res.writeHead(status, {
    'Content-Type': 'application/json',
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type',
  });
  res.end(JSON.stringify(data, null, 2));
}

// ============================================================================
// Request Handlers
// ============================================================================

async function handleExplain(body: unknown): Promise<ExplainResponse> {
  // Validate input
  const parseResult = ExplainRequestSchema.safeParse(body);
  if (!parseResult.success) {
    throw new ValidationError(`Invalid request: ${parseResult.error.message}`);
  }

  const request: ExplainRequest = parseResult.data;

  // Validate directory is allowed
  if (!isPathAllowed(request.directory)) {
    throw new ValidationError(
      `Directory not allowed: ${request.directory}. Check ALLOWED_ROOTS configuration.`
    );
  }

  logger.info('Processing explain request', {
    question: request.question.substring(0, 100),
    directory: request.directory,
  });

  // Create agent and execution loop
  const agent = createCodebaseExplainerAgent(request.directory);
  const loop = new AgentExecutionLoop(agent, process.env.OPENAI_API_KEY!);

  // Run the agent
  const response = await loop.run(request);

  logger.info('Explain request completed', {
    filesExamined: response.metadata.filesExamined,
    toolCalls: response.metadata.toolCalls,
    executionTimeMs: response.metadata.executionTimeMs,
    confidence: response.metadata.confidence,
  });

  return response;
}

// ============================================================================
// HTTP Server
// ============================================================================

const server = createServer(
  async (req: IncomingMessage, res: ServerResponse) => {
    const startTime = Date.now();

    // Handle CORS preflight
    if (req.method === 'OPTIONS') {
      res.writeHead(204, {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
        'Access-Control-Allow-Headers': 'Content-Type',
      });
      res.end();
      return;
    }

    const url = new URL(req.url || '/', `http://localhost:${CONFIG.port}`);

    logger.info('Request received', { method: req.method, path: url.pathname });

    try {
      // Health check
      if (req.method === 'GET' && url.pathname === '/health') {
        return sendJSON(res, 200, {
          status: 'ok',
          name: CONFIG.name,
          version: CONFIG.version,
          uptime: process.uptime(),
        });
      }

      // Info endpoint
      if (req.method === 'GET' && url.pathname === '/') {
        return sendJSON(res, 200, {
          name: CONFIG.name,
          version: CONFIG.version,
          description: 'AI agent that explores and explains codebases',
          architecture: 'Rig-aligned with typed tools and execution loop',
          endpoints: {
            'GET /': 'Agent info',
            'GET /health': 'Health check',
            'POST /explain': 'Explain codebase (main endpoint)',
          },
          tools: [
            'list_directory',
            'read_file',
            'search_code',
            'analyze_imports',
          ],
        });
      }

      // Explain endpoint
      if (req.method === 'POST' && url.pathname === '/explain') {
        const body = await parseBody(req);
        const result = await handleExplain(body);

        logger.info('Request completed', { duration: Date.now() - startTime });
        return sendJSON(res, 200, result);
      }

      // 404 for unknown routes
      sendJSON(res, 404, { error: 'Not found', code: 'NOT_FOUND' });
    } catch (error) {
      const { statusCode, body } = handleError(error);
      logger.error('Request failed', {
        error: body,
        duration: Date.now() - startTime,
      });
      sendJSON(res, statusCode, body);
    }
  }
);

// ============================================================================
// Graceful Shutdown
// ============================================================================

process.on('SIGTERM', () => {
  logger.info('SIGTERM received, shutting down');
  server.close(() => process.exit(0));
});

process.on('SIGINT', () => {
  logger.info('SIGINT received, shutting down');
  server.close(() => process.exit(0));
});

// ============================================================================
// Start Server
// ============================================================================

server.listen(CONFIG.port, () => {
  logger.info('Agent started', {
    name: CONFIG.name,
    version: CONFIG.version,
    port: CONFIG.port,
  });
  console.log(`
╔══════════════════════════════════════════════════════════════╗
║                    CODEBASE EXPLAINER                        ║
║                        v${CONFIG.version}                              ║
╠══════════════════════════════════════════════════════════════╣
║  An AI agent that explores and explains unfamiliar codebases ║
║  Architecture: Rig-aligned with typed tools                  ║
╠══════════════════════════════════════════════════════════════╣
║  Endpoints:                                                  ║
║    GET  /         - Agent info                               ║
║    GET  /health   - Health check                             ║
║    POST /explain  - Explain codebase                         ║
╠══════════════════════════════════════════════════════════════╣
║  Tools: list_directory, read_file, search_code,              ║
║         analyze_imports                                      ║
╚══════════════════════════════════════════════════════════════╝

Server running at http://localhost:${CONFIG.port}
`);
});
